spin_manifest_version = 2

[application]
authors = ["Thorsten Hans <thorsten.hans@fermyon.com>"]
description = ""
name = "spin-deepseek-linode"
version = "0.1.0"

[variables]

ollama_base_url = { required = true }
ollama_model = { default = "deepseek-r1:latest" }
temperature = { default = "0.4" }

[[trigger.http]]
route = "/..."
component = "frontend"

[[trigger.http]]
route = "/api/..."
component = "api"

[component.api]
source = "api/dist/api.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["{{ ollama_base_url }}"]

[component.api.variables]
ollama_base_url = "{{ ollama_base_url }}"
ollama_model = "{{ ollama_model }}"
temperature = "{{ temperature }}"

[component.api.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
workdir = "api"

[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "frontend/dist", destination = "/" }]
environment = { FALLBACK_PATH = "index.html" }

[component.frontend.build]
command = ["npm install", "npm run build"]
workdir = "frontend"
